backend:
  name: git-gateway
  branch: main

media_folder: "src/img/veicoli"
public_folder: "/img/veicoli"

collections:
  - name: "veicoli"
    label: "Veicoli"
    folder: "src/veicoli"
    create: true
    fields:
      - { label: "Marca", name: "marca", widget: "string" }
      - { label: "Modello", name: "modello", widget: "string" }
      - { label: "Anno", name: "anno", widget: "number" }
      - { label: "Descrizione", name: "descrizione", widget: "text" }
      - { label: "Immagine", name: "immagine", widget: "image" }
      - { label: "Stato", name: "stato", widget: "select", options: ["Attivo", "Archiviato"] }